name: arkham-core

language: GHC2021

dependencies:
- base

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- ExtendedDefaultRules
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- RecordWildCards
- StrictData
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UndecidableInstances
- ViewPatterns

build-tools:
- cards-discover

library:
  source-dirs: library
  dependencies:
    - time
    - MonadRandom
    - aeson
    - aeson-casing
    - aeson-diff
    - classy-prelude
    - containers
    - extra
    - lens
    - monoidal-containers
    - mtl >= 2.3.1
    - parsec
    - pretty-simple
    - process
    - random-shuffle
    - safe
    - semialign
    - template-haskell
    - text
    - these
    - these-lens
    - transformers
    - uuid

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts -O0 "-with-rtsopts=-N"
    dependencies:
      - arkham-core
      - hspec
      - hspec-expectations-lifted
      - lens
      - uuid
      - mtl
      - random
      - containers
      - text
